name: Lets Start StarXRobot
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "and user not in [777000, 1087968824]"
          replace: "and user not in [777000, 1087968824, 5463205082]"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'StarXRobot'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: starboihacks369
          commit_user_email: 102808014+starboihacks369@users.noreply.github.com
          commit_author: starboihacks369 <102808014+starboihacks369@users.noreply.github.com>
